[package]
name = "eth-integ"
version = "0.1.0"
edition = "2021"

[dependencies]
web3 = "0.15.0"      
serde = "1.0"        
serde_json = "1.0"   
dotenv = "0.15.0"    
tokio = { version = "1", features = ["full"] } 
